# Generated by Django 4.0.3 on 2022-03-15 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listings',
            name='image',
            field=models.ImageField(default='../static/default.jpg', upload_to='static'),
        ),
    ]
