# Generated by Django 4.0.3 on 2022-03-15 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_listings_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listings',
            name='image',
            field=models.ImageField(default='..auctions/static/default.jpg', upload_to='auctions\\static'),
        ),
    ]
