# Generated by Django 4.0.3 on 2022-03-17 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_auction_listings_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
