# Generated by Django 4.0.3 on 2022-03-20 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listings',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auction_listings',
            name='watchlisted',
            field=models.BooleanField(default=False),
        ),
    ]
