# Generated by Django 4.0.3 on 2022-03-20 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_auction_listings_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_listings',
            name='category',
        ),
    ]
